/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef ARRAYS_AND_STRINGS_H
#define ARRAYS_AND_STRINGS_H

#ifdef _WIN32
#define ARRAYS_AND_STRINGS_EXPORT_FUNC __declspec(dllexport)
#else
#define ARRAYS_AND_STRINGS_EXPORT_FUNC
#endif

#include <stdio.h>

namespace arrays_and_strings {
    class ArraysAndStrings {
        public:
        void ARRAYS_AND_STRINGS_EXPORT_FUNC reverse(char *);
    };
}

#endif
