/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "arrays-and-strings.h"

void arrays_and_strings::ArraysAndStrings::reverse(char *str) {
    char* end = str;
    char tmp;
    if(str){
        while(*end){
          ++end;
        }
        --end;

        while(str < end){
          tmp = *str;
          *str++ = *end;
          *end-- = tmp;
        }
    }
}
