/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <cassert>
#include <string.h>
#include "arrays-and-strings.h"

int main() {
    arrays_and_strings::ArraysAndStrings arraysAndStrings;
    
    char ogStr[]="asdf";
    char reversedStr[]="asdf";
    arraysAndStrings.reverse(reversedStr);
    char expectedStr[]="fdsa";
    
    assert(strcmp(reversedStr, expectedStr) == 0);
    return 0;
}
